default_platform(:ios)

platform :ios do
	before_all do
    	en_ci_utils_init
    end

	lane :build do
		update_app_identifier
		disable_automatic_code_signing
		en_setup_keychain
		set_build_number
		match
		cocoapods
		gym
		publish
	end
  
  	 lane :test do
  	 	cocoapods
  	 	scan(code_coverage: true)
    	slather
	  end

	lane :create_sonar_reports do
	   	test
		en_create_sonar_reports
	 end

   	private_lane :set_build_number do
    	increment_build_number(build_number: en_build_number)
 	 end

 	desc "Validate Pull Request."
  	lane :validate_pr do
   		danger
   		test
 	end

  	private_lane :publish do
    	if ENV['GYM_EXPORT_METHOD'] == "app-store"
     		 produce # create the app in App Store if it doesn't exist
     		 pilot
  	  	else
   	   		crashlytics
   		 end
 	 end

# 	lane :commitFastfile do 
# 		git_add(path: "fastlane/Fastfile")
#		git_commit(path: "fastlane/Fastfile", message: "Update Fastfile")
#	end

	after_all do |lane|
		en_remove_keychain
	end
 
	error do |lane, exception|
		en_remove_keychain
	end
end
